services:
  flight-reservations-tests:
    image: gaumji19/flight-reservations-test-runner:latest
    container_name: flight-reservations-tests
    user: "1000"
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
    volumes:
      # We no longer need to mount the .m2 repository, as dependencies are in the image.
      # But we still need to mount target to get the test results out.
      - ./target:/home/flight-reservations/target
    entrypoint: ""
    command: >
      sh -c "
        while ! curl -sSL http://selenium-hub:4444/wd/hub/status | jq -r '.value.ready' | grep 'true' > /dev/null; do
            echo 'Waiting for the Grid...'
            sleep 1
        done
        echo 'Running tests...'
        # Run tests directly using the pre-compiled classes and dependencies from the image
        java -cp 'target/libs/*:target/classes:target/test-classes' org.testng.TestNG test-suites/flight-reservation.xml || export EXIT_CODE=$?
        exit ${EXIT_CODE:-0}
      "

  selenium-hub:
    image: selenium/hub:4.27
    container_name: selenium-hub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.27
    shm_size: '2g'
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2g'
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443