services:
  flight-reservations:
    image: gaumji19/flight-reservations:latest
    container_name: flight-reservations-tests
    depends_on:
      - chrome
      - firefox
    volumes:
      - ./target:/home/flight-reservations/target
      - /var/jenkins_home/.m2:/root/.m2
    entrypoint: ""
    command: >
      sh -c "
        # 1. Wait for the Grid to be ready
        echo '--- WAITING FOR SELENIUM GRID ---'
        while ! curl -sSL http://selenium-hub:4444/wd/hub/status | jq -r '.value.ready' | grep 'true' > /dev/null; do
            echo 'Waiting for the Grid to be ready...'
            sleep 1
        done;
        echo '--- GRID IS READY, RUNNING TESTS ---'

        # ✅ ADDITION: Fail fast if essential variables are not set by the CI/CD platform.
        : \"$${TEST_SUITE:?ERROR: TEST_SUITE variable is not set}\"
        : \"$${BROWSER:?ERROR: BROWSER variable is not set}\"
        : \"$${THREAD_COUNT:?ERROR: THREAD_COUNT variable is not set}\"
        : \"$${ENV:?ERROR: ENV variable is not set}\"

        # 2. Run tests using variables passed from Jenkins.
        # Quoting variables (e.g., \"$${...}\") is a best practice for safety.
        java -javaagent:'libs/aspectjweaver-1.9.20.1.jar' \
             -cp 'libs/*' \
             -Dallure.results.directory=target/allure-results \
             -Denv=\"$${ENV}\" \
             -Dselenium.grid.enabled=true \
             -Dselenium.grid.hubHost=$${HUB_HOST:-selenium-hub} \
             -Dbrowser=\"$${BROWSER}\" \
             org.testng.TestNG \
             -parallel tests \
             -threadcount \"$${THREAD_COUNT}\" \
             \"test-suites/$${TEST_SUITE}\"
      "
  selenium-hub:
    image: selenium/hub:4.27
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.27
    shm_size: '2g'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2g'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443