services:
  flight-reservations:
    image: gaumji19/flight-reservations:latest
    container_name: flight-reservations-tests
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
    volumes:
      - ./target:/home/flight-reservations/target
      - /var/jenkins_home/.m2:/root/.m2
    entrypoint: ""
    command: >
      sh -c "
        while ! curl -sSL http://selenium-hub:4444/wd/hub/status | jq -r '.value.ready' | grep 'true' > /dev/null; do
            echo 'Waiting for the Grid...'
            sleep 1
        done
        echo 'Running tests...'
        mvn clean test -Dsurefire.suiteXmlFiles=test-suites/flight-reservation.xml || export EXIT_CODE=$?
        chown -R 1000:1000 target
        exit ${EXIT_CODE:-0}
      "

  selenium-hub:
    image: selenium/hub:4.27
    container_name: selenium-hub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.27
    shm_size: '2g'
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2g'
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443