services:
  flight-reservations:
    image: gaumji19/flight-reservations:latest
    container_name: flight-reservations-tests
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
    volumes:
      - ./target:/home/flight-reservations/target
      - /var/jenkins_home/.m2:/root/.m2
    entrypoint: ""
    command: >
      sh -c "
        echo '--- CONTAINER DIAGNOSTICS (START) ---'
        echo 'Current Working Directory inside container:' $(pwd)
        ls -la /home/flight-reservations/
        # Simple test to confirm execution proceeds
        echo 'Point A: Before Grid Check'

        while ! curl -sSL http://selenium-hub:4444/wd/hub/status | jq -r '.value.ready' | grep 'true' > /dev/null; do
            echo 'Waiting for the Grid to be ready...'
            sleep 1
        done

        echo 'Point B: After Grid Check - Selenium Grid is up and running. Running tests...'

        echo 'Point C: After \"Running tests\" message - This line should definitely appear!'
      
        # We will re-introduce Maven and other checks once Point C appears reliably.
      
        echo 'Point D: End of script reached successfully.'
        exit 0
      "
  selenium-hub:
    image: selenium/hub:4.27
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.27
    shm_size: '2g'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2g'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443