services:
  flight-reservations:
    image: gaumji19/flight-reservations:latest
    container_name: flight-reservations-tests
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
    volumes:
      - ./target:/home/flight-reservations/target
    # ✅ Reset the image's default entrypoint
    entrypoint: ""

    # ✅ THIS IS THE FIX: The 'java' command is now on a single line
    command: >
      sh -c "
        # Wait for the Grid to be ready
        while ! curl -sSL http://selenium-hub:4444/wd/hub/status | jq -r '.value.ready' | grep 'true' > /dev/null; do
            echo 'Waiting for the Grid to be ready...'
            sleep 1
        done

        echo 'Selenium Grid is up and running. Running tests...'
        java -cp 'libs/*' -Dselenium.grid.hubHost=${HUB_HOST} org.testng.TestNG test-suites/flight-reservation.xml
      "
  selenium-hub:
    image: selenium/hub:4.27
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.27
    shm_size: '2g'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2g'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
